name: Spacegame.Web
on:
 push:
   branches: [ main ]
   paths-ignore:
    - .github/**
env:
  API_APP_NAME: 'leaderboardgh'
  WEB_APP_NAME: 'spacegamegh'

jobs:
    build_api_app:
      name: 🧪 Build API App
      runs-on: orgrunner
      
      steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
        
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
             
      - name: Publish
        run: dotnet publish --no-restore -c Release
        working-directory: ./Tailspin.SpaceGame.LeaderboardContainer
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: spacegameleaderboard
          path: ./Tailspin.SpaceGame.LeaderboardContainer/bin/Release/netcoreapp3.1/publish/
