name: CI-dkr

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: 📦 GCR
    runs-on: ubuntu-latest    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TEST_PAT }}
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Tailspin.SpaceGame.LeaderboardContainer/Dockerfile
          push: true
          tags: |
            ghcr.io/canarysplayground/leaderboard/dev:latest  
            ghcr.io/canarysplayground/leaderboard/dev:${{ github.sha }}
       
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    needs: build
    steps:

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'mytestdkr'
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        images: 'ghcr.io/canarysplayground/leaderboard/dev:${{ github.sha }}'
  
